name: build image

on:
  workflow_dispatch:

jobs:
  call:
    if: needs.update-version.outputs.status == 'true'
    uses: donderjoekel/build-workflow/.github/workflows/build-on-call.yml@master
    secrets: inherit
