name: build image

on:
  workflow_dispatch:
  push:
    branches:
      - nightly
    paths:
      - 'VERSION.json'

jobs:
  call:
    uses: donderjoekel/build-workflow/.github/workflows/build-on-call-no-smoke.yml@master
    secrets: inherit
