name: update-versions

on:
  workflow_dispatch:

jobs:
  get:
    runs-on: ubuntu-latest
    steps:
    - name: Get
      shell: bash
      env:
       TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run : |
        response_json= $(curl -L \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer $TOKEN" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/donderjoekel/prowlarr/releases/latest)
